# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20160320_1939'),
        ('accounts', '0002_auto_20160320_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Approved'), (2, 'Denied')], default=0)),
            ],
            options={
                'verbose_name_plural': "Students' chooses",
                'verbose_name': "Student's choose",
            },
        ),
        migrations.CreateModel(
            name='Choosing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('phase', models.IntegerField(choices=[(0, 'Preparation'), (1, 'Choosing of courses'), (2, 'Evaluating of options'), (3, 'Changes in choosings'), (4, 'Creating groups'), (5, 'Group changes'), (6, 'Finished')])),
                ('active', models.BooleanField(default=True)),
                ('allow_teacher_requests', models.BooleanField(default=False)),
                ('courses_min', models.IntegerField()),
                ('courses_max', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('for_grade', models.IntegerField(blank=True, default=None, null=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory')),
                ('denied_courses', models.ManyToManyField(blank=True, to='courses.Course')),
            ],
            options={
                'ordering': ('priority',),
                'verbose_name_plural': 'Choosing configurations',
                'verbose_name': 'Choosing configuration',
            },
        ),
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Approved'), (2, 'Denied')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosing.Choose')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
            options={
                'verbose_name_plural': 'Requests for teachers',
                'verbose_name': 'Request for teacher',
            },
        ),
        migrations.AddField(
            model_name='choose',
            name='choosing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosing.Choosing'),
        ),
        migrations.AddField(
            model_name='choose',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='choose',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherrequest',
            unique_together=set([('choose', 'teacher')]),
        ),
    ]
