# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choosing', '0002_auto_20160321_0104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choose',
            unique_together=set([('student', 'choosing', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='teacherrequest',
            unique_together=set([]),
        ),
    ]
