# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160411_0623'),
        ('courses', '0003_auto_20160411_0623'),
        ('choosing', '0004_auto_20160411_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('choosing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosing.Choosing')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='deniedcombination',
            name='choosing',
        ),
        migrations.RemoveField(
            model_name='deniedcombination',
            name='course',
        ),
        migrations.RemoveField(
            model_name='deniedcombination',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='DeniedCombination',
        ),
        migrations.AlterUniqueTogether(
            name='resolvedcombination',
            unique_together=set([('choosing', 'course', 'teacher')]),
        ),
    ]
