# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160320_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('classroom', 'user'), 'verbose_name': 'Študent', 'verbose_name_plural': 'Študenti'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Učiteľ', 'verbose_name_plural': 'Učitelia'},
        ),
    ]
