# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='accounts.Teacher'),
        ),
    ]
