# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160320_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-active', 'acronym'), 'verbose_name': 'Predmet/Seminár', 'verbose_name_plural': 'Predmety/Semináre'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Kategória kurzov', 'verbose_name_plural': 'Kategórie kurzov'},
        ),
        migrations.AlterModelOptions(
            name='subjectclass',
            options={'verbose_name': 'Trieda predmetov', 'verbose_name_plural': 'Triedy predmetov'},
        ),
    ]
